version: "3"
services:
  registry:
    restart: unless-stopped
    image: registry:2
    network_mode: host
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
      REGISTRY_AUTH: token
      REGISTRY_AUTH_TOKEN_REALM: http://localhost:${PORT}/token
      REGISTRY_AUTH_TOKEN_SERVICE: localhost:${PORT}
      REGISTRY_AUTH_TOKEN_ISSUER: auth.docker.chalmers.it
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /certs/RootCA.crt
    volumes:
      - ./certs:/certs

  redis:
    image: redis:6.2
    ports:
      - ${REDIS_PORT}:6379
